name: Notify

on:
  workflow_call:
    inputs:
      job-name:
        description: 'Job Name'
        required: true
        type: string
      app-url:
        description: 'App URL'
        required: true
        type: string
      status:
        description: 'Build Status'
        required: true
        type: string
    secrets:
      TELEGRAM_TO:
        required: true
      TELEGRAM_TOKEN:
        required: true

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - uses: appleboy/telegram-action@master
        with:
          to: ${{ vars.TELEGRAM_BUILD_BOT_ID }}
          token: ${{ vars.TELEGRAM_BUILD_BOT_TOKEN }}
          format: markdown
          message: |
            ğŸš€ *M2U/${{ inputs.job-name }} ${{ github.run_number }}* 
            ${{ inputs.status == 'success' && '- Success âœ…' || '- Failed âŒ' }}
            ğŸ““ Repository: *${{ github.repository }}*
            ğŸ‘¤ Owner: *${{ github.repository_owner }}*
            ğŸ«µğŸ» Actor: *${{ github.actor }}*
            ğŸ•ï¸ Branch: *${{ github.ref_name }}*
            ğŸ“Ÿ Action: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
            ğŸ¯ Commit: https://github.com/${{ github.repository }}/commit/${{ github.sha }}
            ğŸ”— App URL: *${{ inputs.app-url }}*
